### ISSUE TITLE
能不能增加多一点

### ISSUE THREAD

**Issue by lihonest** [cxfksword/iptv#1]
大神，想用你的直播表自用，无奈小白一个，GitHub不是那么懂，能不能增加广东一些台，和香港的一些台（小飞侠里面香港的一些频道），自用。感恩。

**Comment by cxfksword** [comment]
这个是我自己自用的，建议你fork后自己再改下

**Comment by lihonest** [comment]
> 这个是我自己自用的，建议你fork后自己再改下
好的，但是你更新之后，我修改的，能否同步更新你的？能加个微信吗？

**Comment by cxfksword** [comment]
> > 这个是我自己自用的，建议你fork后自己再改下
> > 好的，但是你更新之后，我修改的，能否同步更新你的？能加个微信吗？

可以用GithubAction实现，不过要有编程基础，建议你用下面tg频道公共源的，置顶有：
[https://t.me/vamoschucktv](https://t.me/vamoschucktv)

**Comment by lihonest** [comment]
> > > 这个是我自己自用的，建议你fork后自己再改下
> > > 好的，但是你更新之后，我修改的，能否同步更新你的？能加个微信吗？
> 
> 可以用GithubAction实现，不过要有编程基础，建议你用下面tg频道公共源的，置顶有： https://t.me/vamoschucktv

大佬，可可以加个电报沟通啊？我加入群了，你可否联系一下我？叫lihong
