### ISSUE TITLE
请教下有没有什么播放器支持这种用#分隔同一个名字的多个源的的m3u的

### ISSUE THREAD

**Issue by linsongze** [cxfksword/iptv#3]
#EXTINF:-1 tvg-id="1" tvg-name="CCTV1" tvg-logo="http://epg.51zmt.top:8000/tb1/CCTV/CCTV1.png" tvg-speed="10MB/s" tvg-rez="1920x1080" group-title="央视",CCTV-1综合
http://39.135.32.236:6610/PLTV/77777777/224/3221225674/index.m3u8?$广西移动#http://39.135.32.236:6610/PLTV/77777777/224/3221225674/index.m3u8?#http://39.135.55.105:6610/PLTV/88888888/224/3221226995/index.m3u8?servicetype=1#http://39.135.55.105:6610/PLTV/88888888/224/3221225922/index.m3u8?servicetype=1#http://39.135.32.236:6610/PLTV/77777777/224/3221225888/index.m3u8?
你好，，，我看你的源文件里面 同一个台的多个源，是用#进行分割的，，，请教下，你那边是用什么播放器加载，可以切换多个源

**Comment by cxfksword** [comment]
我是appletv的iiva，android的话，可以试下火星直播，不过android下个电视族app不是比m3u8好用😂
